# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: (C) 2025 Siemens
#
# Authors:
#  Eugen Kremer <eugen.kremer@siemens.com>

name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    container:
      image: gcc:15.2.0-trixie
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        apt update --fix-missing
        apt install -y --no-install-recommends cmake ccache lcov \
          libp11-kit-dev \
          bsdextrautils opensc libengine-pkcs11-openssl gnutls-bin squashfs-tools rauc python3-pip xxd
        pip3 install reuse --break-system-packages
    
    - name: Configure and build
      run: |
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug
        cmake --build build -j $(nproc)
    
    - name: Run tests
      run: ./tests/runner.sh
    
    - name: Generate coverage report and badge
      if: success()
      run: |
        lcov --capture --directory build --output-file coverage.info --exclude '/usr/*'
        lcov --list coverage.info
    
        COVERAGE=$(lcov --summary coverage.info 2>&1 | grep "lines......" | awk '{print $2}' | sed 's/%//')
        echo "Coverage: $COVERAGE%"
        
        # Determine badge color using awk
        COLOR=$(awk -v cov="$COVERAGE" 'BEGIN {
          if (cov >= 80) print "brightgreen"
          else if (cov >= 60) print "yellow"
          else print "red"
        }')
        
       
        # Download SVG badge from shields.io
        mkdir -p badge
        curl -o badge/coverage.svg "https://img.shields.io/badge/coverage-${COVERAGE}%25-${COLOR}"
    
    - name: Deploy badge to GitHub Pages
      if: success() && github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./badge
        destination_dir: badge
        keep_files: true

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-openssl
            mingw-w64-ucrt-x86_64-p11-kit

      - name: Build project with CMake (MinGW)
        shell: msys2 {0}
        run: |
          cmake -S $GITHUB_WORKSPACE -B $GITHUB_WORKSPACE/build -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Debug
          cmake --build $GITHUB_WORKSPACE/build -j $(nproc)
